"use client";

/* eslint-disable @next/next/no-img-element */

import { useEffect, useState } from "react";
import { formatPrice } from "../../catalog";

type ReceiptOrder = { orderNumber: string; branchName: string; city: string; customerName: string; phone: string; address: string; fulfilment: string; subtotal: number; deliveryFee: number; total: number; paymentMethod: string; paymentStatus: string; status: string; source: string; cashierName: string; notes: string; createdAt: string; items: Array<{ id: number; itemName: string; variantLabel: string; choice: string; unitPrice: number; quantity: number; lineTotal: number }> };

export default function ReceiptClient({ orderNumber, token, pos }: { orderNumber: string; token: string; pos: boolean }) {
  const [order, setOrder] = useState<ReceiptOrder | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/receipts/${encodeURIComponent(orderNumber)}${token ? `?token=${encodeURIComponent(token)}` : ""}`, { cache: "no-store" }).then(async (response) => { const body = await response.json() as { order?: ReceiptOrder; error?: string }; if (!response.ok || !body.order) throw new Error(body.error ?? "Receipt not found."); setOrder(body.order); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Receipt not found.")); }, [orderNumber, token]);
  if (error) return <main className="receipt-page"><section className="receipt-error"><img src="/puffy-pops-logo.png" alt="Puffy Pops" /><h1>Receipt unavailable</h1><p>{error}</p><a href={pos ? "/" : "/menu"}>Go back</a></section></main>;
  if (!order) return <main className="receipt-page"><section className="receipt-error"><p>Preparing your receipt…</p></section></main>;
  return <main className="receipt-page"><div className="receipt-actions no-print"><a href={pos ? "/" : "/menu"}>{pos ? "← Puffy Pops home" : "← Back to menu"}</a><button type="button" onClick={() => window.print()}>Print / save receipt</button></div><article className="receipt-paper"><header><img src="/puffy-pops-logo.png" alt="Puffy Pops" /><p><strong>{order.branchName}</strong><span>{order.city}</span></p></header><div className="receipt-title"><span className="success-mark">✓</span><p>{order.source === "pos" ? "Payment received" : "Order received"}</p><h1>Thank you!</h1><small>{new Date(order.createdAt).toLocaleString("en-EG", { dateStyle: "medium", timeStyle: "short" })}</small></div><section className="receipt-meta"><div><span>Receipt / order</span><strong>{order.orderNumber}</strong></div><div><span>Order type</span><strong>{order.source === "pos" ? "Counter sale" : order.fulfilment === "pickup" ? "Online pickup" : "Online delivery"}</strong></div><div><span>Payment</span><strong>{order.paymentMethod === "card" ? "Card" : "Cash"} · {order.paymentStatus.replaceAll("_", " ")}</strong></div>{order.cashierName && <div><span>Cashier</span><strong>{order.cashierName}</strong></div>}</section><section className="receipt-items"><div className="receipt-line receipt-line-head"><span>Item</span><span>Qty</span><span>Total</span></div>{order.items.map((item) => <div className="receipt-line" key={item.id}><span><strong>{item.itemName}</strong><small>{item.variantLabel}{item.choice ? ` · ${item.choice}` : ""}</small></span><span>{item.quantity}</span><span>{formatPrice(item.lineTotal)}</span></div>)}</section><section className="receipt-totals"><div><span>Subtotal</span><strong>{formatPrice(order.subtotal)}</strong></div>{order.deliveryFee > 0 && <div><span>Delivery</span><strong>{formatPrice(order.deliveryFee)}</strong></div>}<div className="receipt-grand"><span>Total</span><strong>{formatPrice(order.total)}</strong></div></section><section className="receipt-customer"><div><span>Customer</span><strong>{order.customerName}</strong></div>{order.source !== "pos" && <><div><span>Phone</span><strong>{order.phone}</strong></div><div><span>{order.fulfilment === "pickup" ? "Pickup" : "Deliver to"}</span><strong>{order.address}</strong></div></>}{order.notes && <div><span>Notes</span><strong>{order.notes}</strong></div>}</section><footer><strong>Spreading joy, one bite at a time.</strong><span>Keep this receipt for your records.</span></footer></article></main>;
}
